version: "3"

services:
  ai-search:
    container_name: ai-search
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - OLLAMA_API_HOST=OLLAMA_API_HOST
      - OLLAMA_API_PORT=OLLAMA_API_PORT
    restart: always
    ports:
      - 3000:3000
